### ISSUE TITLE
make -j4 fails

### ISSUE THREAD

**Issue by sjackman** [ncbi/ncbi-vdb#16]
`make -j1` does however succeed.
```
mv: rename dna-reverse-cmpl.pic.o to align-reader-dna-reverse-cmpl.pic.o: No such file or directory
mv: rename reference-cmn.pic.o to align-reader-reference-cmn.pic.o: No such file or directory
…
mv: rename align-ref-name.pic.o to axf-align-ref-name.pic.o: No such file or directory
mv: rename align-ref-seq-id.pic.o to axf-align-ref-seq-id.pic.o: No such file or directory
```
For a complete log, see https://gist.githubusercontent.com/sjackman/ba0838ed694a09007da2a09d6d355c41/raw/afec628ebc5df61f5c703da2545f3090699dad09/05.make
and https://gist.github.com/sjackman/ba0838ed694a09007da2a09d6d355c41

**Comment by kwrodarmer** [comment]
Our make is currently recursive, and it runs parallel builds internally - you gain nothing by running the outer make in parallel.

**Comment by kwrodarmer** [comment]
By the way, we will be releasing a new make system that will be happy to support parallel compilation on your command line (it already performs it internally) and will be much faster. I don't have any promise for a release date, since we are fairly heavily loaded with work right now and our build works, so it isn't able to preempt other very high priority work.
