### ISSUE TITLE
ktst test failure

### ISSUE THREAD

**Issue by prehensilecode** [ncbi/ncbi-vdb#34]
Getting a fatal error in test-ktst:

OS: RHEL 8
Compiler: GCC 9.2.0

```
Run /home/myname/ncbi-outdir/ncbi-vdb/linux/gcc/x86_64/rel/test-bin/test-ktst
Running 12 test cases...
Parameter (0 s)
Requires (0 s)
ParentProcess (0 s)
ChildProcessOk (0 s)
/ifs/opt/src/ncbi/ncbi-vdb-2.10.9/test/ktst/ktsttest.cpp(123): fatal error in fixture: ChildProcessFail: failure in a child process
ChildProcessFail aborted
ChildProcessFail (0 s)
fatal error: signal: SIGFPE(Floating point exception)
/ifs/opt/src/ncbi/ncbi-vdb-2.10.9/test/ktst/ktsttest.cpp(129): last checkpoint
Test is aborted
ChildProcessAbort (0 s)
child process timed out
ChildProcessTimeout (1 s)
ArgHandlerCalled (0 s)
SharedSucceed (0 s)
/ifs/opt/src/ncbi/ncbi-vdb-2.10.9/test/ktst/ktsttest.cpp:156: error in "SharedFailed.Shared": check ok failed
SharedFailed (0 s)
/ifs/opt/src/ncbi/ncbi-vdb-2.10.9/test/ktst/ktsttest.cpp:156: error in "SharedFailedAndDetected.Shared": check ok failed
SharedFailedAndDetected (0 s)
SharedSucceedInBlock (0 s)
```

**Comment by aboshkin** [comment]
This output is normal. The test-ktst suite is the unit-test framework testing itself; the error messages are from test cases expected to fail in order to test the framework's ability to detect failing tests.

There should be a message with the count of failed tests and the total execution time at the end of every test suite's execution. Do you see one? An example:

*** No errors detected (1 s total)

**Comment by prehensilecode** [comment]
Yes, there is:
```
*** No errors detected (0 s total)
```

However, later on:
```
Run /home/myname/ncbi-outdir/ncbi-vdb/linux/gcc/x86_64/rel/test-bin/test-kdb
Running 10 test cases...
KDBManagerVPathOpenDB_Local (0 s)
KDBManagerVPathOpenDB_Local_Table (0 s)
KDBManagerVPathOpenDB_Local_BadPath (0 s)
KDBManagerVPathOpenDB_Remote (0 s)
KDBManagerVPathOpenDB_Remote_NoCache (0 s)
/ifs/opt/src/ncbi/ncbi-vdb-2.10.9/test/kdb/remote_open_test.cpp(257): last checkpoint before exception "RemoteDBFixture::Resolve: VResolverQuery failed"
KDBManagerVPathOpenDB_Remote_Table (60 s)
KDBManagerVPathOpenDB_Remote_BadPath (0 s)
KDBManagerVPathType (0 s)
ColumnBlobRead_basic (0 s)
ColumnBlobRead_insufficient_buffer (0 s)

*** 1 failure detected in test suite "KdbTestSuite"
make[2]: *** [/ifs/opt/src/ncbi/ncbi-vdb-2.10.9/build/Makefile.env:354: runtests] Error 3
make[2]: Leaving directory '/ifs/opt/src/ncbi/ncbi-vdb-2.10.9/test/kdb'
make[1]: *** [/ifs/opt/src/ncbi/ncbi-vdb-2.10.9/build/Makefile.targets:91: kdb_runtests] Error 2
make[1]: Leaving directory '/ifs/opt/src/ncbi/ncbi-vdb-2.10.9/test'
make: *** [Makefile:47: test] Error 2
```

I have attached the full output of "make test".
[Make.test.output.txt](https://github.com/ncbi/ncbi-vdb/files/6012515/Make.test.output.txt)

**Comment by aboshkin** [comment]
This looks like a network timeout. Please re-run the tests.

**Comment by prehensilecode** [comment]
Ran tests again with "make -k". These were the failures:
```
*** 1 failure detected in test suite "KdbTestSuite"
*** 1 failure detected in test suite "VdbTestSuite"
*** 1 failure detected in test suite "NgsReferenceTestSuite"
*** 2 failures detected in test suite "CachingSuite"
```

Full output attached.
[Make.test.output2.txt](https://github.com/ncbi/ncbi-vdb/files/6016310/Make.test.output2.txt)

**Comment by aboshkin** [comment]
@prehensilecode thank you for providing the full output of the test run. All the errors that you see are caused by networking timeouts encountered while trying to download data from NCBI. Our team has no control over the networking part; we have been working on fortifying our tools and test suites against the timeouts, and the upcoming release will be more resilient. Meanwhile, all I can recommend is, try running the tests again. 

If this helps, here's how to spot a network timeout-triggered problem in the tests. Somewhere above the "failure(s) detected" line there will be an error message from one of the tests, like in this snippet from the output file you provided:

/ifs/opt/src/ncbi/ncbi-vdb-2.10.9/test/ngs/ngstest_reference.cpp(538): last checkpoint before exception "NGS_ReadCollectionMake(SRR496123) failed"
CSRA1_NGS_ReferenceNotLocalSRR413283 (60 s)

Note the "(60 s)" on the line following the error message. This is the duration of the test case; when it is a multiple of 60 seconds you can be certain that this is a network timeout. Normally individual test cases in these suites should not take more than a few seconds; most of them will finish in under 1s.

I hope this helps a bit and thank you for your patience.

**Comment by prehensilecode** [comment]
Anatoly: Thanks for taking the time to explain.
