### ISSUE TITLE
Please remove explicit -m32/-m64 switch

### ISSUE THREAD

**Issue by tillea** [ncbi/ncbi-vdb#8]
Hi,

I received a [bug report for the Debian package](https://bugs.debian.org/836129) and this [patch](https://anonscm.debian.org/cgit/debian-med/ncbi-vdb.git/tree/debian/patches/remove_-m64_flag.patch) solves the issue.  Please note that there are strong opinions that -m32 and -m64 switches are doing more harm than good in general.

Kind regards

```
     Andreas.
```

**Comment by kwrodarmer** [comment]
Can you elaborate?

**Comment by tillea** [comment]
On Wed, Aug 31, 2016 at 05:56:19AM -0700, kwrodarmer wrote:
> Can you elaborate?

As the bug report says: -m32, -m64, and the like are never needed for
native compilation.

In case you do not do any cross-compilation it does more harm than good.
If you do not believe feel free to ignore this issue but the Debian
packages will be build without these options since it is ensured that
there is no cross-compilation.

Kind regards

      Andreas.

-- 
http://fam-tille.de

**Comment by kwrodarmer** [comment]
Our source code is not always needed for native compilation, which is why we added the switches in the first place. This is part of the problem we had with autoconf and the general philosophy of having the build host define the target.

Still curious about the harm they do, however.

**Comment by kwrodarmer** [comment]
> The x32 build of ncbi-vdb failed:
>
>  /usr/include/features.h:364:25: fatal error: sys/cdefs.h: No such file or directory
>   #  include <sys/cdefs.h>
>
> That's because it was looking for the amd64 version of this header,
> because the build system explicitly specified -m64.  Please remove
> this flag -- -m32, -m64, and the like are never needed for native
> compilation, and package builds should use them only in special cases.

So please explain - are you saying that you can't compile with `-m64` enabled?

**Comment by tillea** [comment]
On Wed, Aug 31, 2016 at 07:30:05AM -0700, kwrodarmer wrote:
> Our source code is not always needed for native compilation, which is why we added the switches in the first place. This is part of the problem we had with autoconf and the general philosophy of having the build host define the target.
> 
> Still curious about the harm they do, however.

As written in the bug report https://bugs.debian.org/836129 which I
linked to in the first place it breaks build on x32 architecture.

Kind regards

     Andreas.

-- 
http://fam-tille.de

**Comment by kwrodarmer** [comment]
Hi Andreas and all readers:

The report that you want to make is that we have no build settings to support x32, which is true. We allow building for x86, although we do not officially support it. Here is some historical background.

There have been two events that make 32-bit builds untenable:

1. there have been some caching constants introduced in the past that exceed 32-bit limits
2. we integrated "Judy arrays" into our code base, and their design does not permit proper application development in an architecture neutral way.

In particular, the Judy arrays are used in many cases to map from some integer to a 64-bit word. Since judy arrays use architecture-specific word sizes, they are only capable of mapping an integer to a 32-bit word under x86 and x32. We _do_ have workaround code in all known places, but we no longer test our code under 32-bits and cannot confirm that all cases have been handled or even that the workarounds are functional.

We have written a replacement for Judy that _is_ designed for applications to work cross-architecture, and that could be a possibility for the future, if we want to ensure proper operation.

The problem with testing has to do with the size of data we manage. **ncbi-vdb** is a big-data warehousing technology. I was hearing someone mention how many TB of data are on github the other day, and we all had a laugh. The VDB system in the SRA ingests between 30 and 60 TB of data per day on average, and serves around 70 TB per day over HTTP (soon to be HTTPS). That latter figure totally ignores the data served internally to our production systems. Trying to exercise this system within a 2GB application address space is something we don't think is productive.

So we can look at providing support for an x32 build, although since we can't guarantee that it works, I am not sure what the point of it would be. I'm more concerned about Debian providing 32-bit packages to work with the SRA. What do you think?

**Comment by tillea** [comment]
On Fri, Sep 02, 2016 at 08:00:00AM -0700, kwrodarmer wrote:
> ...

Thanks for the explanation.

> So we can look at providing support for an x32 build, although since we can't guarantee that it works, I am not sure what the point of it would be. I'm more concerned about Debian providing 32-bit packages to work with the SRA. What do you think?

Well, my intention to package ncbi-vdb to get SRA working and usually
this is done in Debian on as many release architectures as it is
possible.  If this approach is technical not sensible the architectures
should be restricted.  So I trust your insight as upstream authors on
what architecture the software should be distributed.

Kind regards

       Andreas.

-- 
http://fam-tille.de
